package com.enercon.siteuser.dao;

public class SiteUserSQLC {
	
public static final String SELECT_EB_DETAIL =
		" SELECT S_EB_ID FROM TBL_WEC_MASTER WHERE S_WEC_ID = ?";

public static final String GET_EB_MASTER_FOR_READING =
	"SELECT B.D_READING_DATE,A.S_EB_ID,C.S_MP_ID,B.N_VALUE,B.N_ACTUAL_VALUE,B.S_REMARKS FROM TBL_EB_MASTER A LEFT OUTER JOIN " +
	" TBL_EB_READING B ON A.S_EB_ID = B.S_EB_ID LEFT OUTER JOIN TBL_MP_MASTER C ON " +
	" B.S_MP_ID = C.S_MP_ID WHERE A.S_SITE_ID = ? AND B.D_READING_DATE = ? AND A.S_STATUS = 1 AND C.S_STATUS = 1 AND C.S_MP_SHOW IN ('EB','BOTH') " +
	" AND C.S_READ_TYPE IN (?,'A') AND B.S_READING_TYPE IN('D','I') ";

public static final String GET_EB_MASTER_FOR_READING_PAGED_PART_2 =
	" AND A.S_EB_ID IN (SELECT B.S_EB_ID FROM (SELECT Z.*, ROWNUM R FROM (SELECT A.S_EB_ID FROM TBL_EB_MASTER A, TBL_EB_MFACTOR B, " +
	" TBL_CUSTOMER_MASTER C WHERE A.S_FEDER_ID IS NULL AND A.S_EB_ID = B.S_EB_ID AND A.S_SITE_ID=? AND A.S_STATUS = 1 " +
	" AND A.S_CUSTOMER_ID = C.S_CUSTOMER_ID AND ? BETWEEN B.D_FROM_DATE AND B.D_TO_DATE ORDER BY S_EBSHORT_DESCR ) Z WHERE ROWNUM <= ?) B WHERE R >= ?)";

public static final String GET_EB_MASTER_FOR_READING_MAX =
	"SELECT B.D_READING_DATE,A.S_EB_ID,C.S_MP_ID,B.N_VALUE,B.N_ACTUAL_VALUE,B.S_REMARKS FROM TBL_EB_MASTER A LEFT OUTER JOIN " +
	" TBL_EB_READING B ON A.S_EB_ID = B.S_EB_ID LEFT OUTER JOIN TBL_MP_MASTER C ON " +
	" B.S_MP_ID = C.S_MP_ID WHERE A.S_SITE_ID = ? AND B.S_READING_TYPE IN (?,'I') AND B.D_READING_DATE IN (select max(d_reading_date) from tbl_eb_reading where " +
	" S_READING_TYPE IN (?,'I') and TO_CHAR(d_reading_date,'MM') = ? and TO_CHAR(d_reading_date,'yyyy') = ? and A.S_EB_ID = tbl_eb_reading.s_eb_id) AND A.S_STATUS = 1 AND C.S_STATUS = 1 " +
	" AND C.S_MP_SHOW IN ('EB','BOTH') AND C.S_READ_TYPE IN (?,'A') " +
	" AND A.S_EB_ID IN (SELECT B.S_EB_ID FROM (SELECT Z.*, ROWNUM R FROM (SELECT A.S_EB_ID FROM TBL_EB_MASTER A, TBL_EB_MFACTOR B, " +
	" TBL_CUSTOMER_MASTER C WHERE A.S_FEDER_ID IS NULL AND A.S_EB_ID = B.S_EB_ID AND A.S_SITE_ID=? AND A.S_STATUS = 1 " +
	" AND A.S_CUSTOMER_ID = C.S_CUSTOMER_ID AND ? BETWEEN B.D_FROM_DATE AND B.D_TO_DATE ORDER BY S_EBSHORT_DESCR ) Z WHERE ROWNUM <= ?)" +
	" B WHERE R >= ?) ORDER BY B.S_REMARKS DESC,C.N_SEQ_NO";

public static final String GET_WEC_GENERATION = 
	"SELECT SUM(A.N_VALUE) AS CUMGEN,SUM(A.N_ACTUAL_VALUE) AS TOTGEN FROM TBL_WEC_READING A, TBL_WEC_MASTER B WHERE A.d_READING_DATE = ? AND A.S_EB_ID = ? " +
	" AND A.S_MP_ID = '0808000022' AND A.S_WEC_ID = B.S_WEC_ID AND B.S_STATUS = 1 AND A.S_READING_TYPE IN ('D','I')"; //0808000022 = GENERATION

public static final String GET_WEC_GENERATION_BY_FEDER = 
	"SELECT SUM(N_ACTUAL_VALUE) AS TOTGEN FROM TBL_WEC_READING A, TBL_WEC_MASTER D, TBL_FEDER_MASTER B, TBL_EB_MASTER C " +
	" WHERE A.d_READING_DATE = ? AND B.S_FEDER_ID = ? AND C.S_FEDER_ID = B.S_FEDER_ID AND A.S_EB_ID = C.S_EB_ID AND D.S_WEC_ID = A.S_WEC_ID " +
	" AND A.S_MP_ID = '0808000022' AND D.S_STATUS = 1 AND A.S_READING_TYPE IN ('D','I')"; //0808000022 = GENERATION

public static final String GET_WEC_GENERATION_BY_FEDER_BY_MONTH = 
	"SELECT SUM(N_ACTUAL_VALUE) AS TOTGEN FROM TBL_WEC_READING A, TBL_WEC_MASTER D, TBL_FEDER_MASTER B, TBL_EB_MASTER C " +
	" WHERE A.d_READING_DATE BETWEEN ? AND ? AND B.S_FEDER_ID = ? AND C.S_FEDER_ID = B.S_FEDER_ID AND A.S_EB_ID = C.S_EB_ID AND D.S_WEC_ID = A.S_WEC_ID " +
	" AND A.S_MP_ID = '0808000022' AND D.S_STATUS = 1 AND A.S_READING_TYPE IN ('D','I')"; //0808000022 = GENERATION

public static final String GET_WEC_GENERATION_BY_FEDER_GROUP_EB = 
	"SELECT A.S_EB_ID,SUM(N_VALUE) AS CUMGEN,SUM(N_ACTUAL_VALUE) AS TOTGEN FROM TBL_WEC_READING A, TBL_WEC_MASTER D, TBL_FEDER_MASTER B, TBL_EB_MASTER C " +
	" WHERE A.d_READING_DATE = ? AND B.S_FEDER_ID = ? AND C.S_FEDER_ID = B.S_FEDER_ID AND A.S_EB_ID = C.S_EB_ID AND D.S_WEC_ID = A.S_WEC_ID " +
	" AND A.S_MP_ID = '0808000022' AND D.S_STATUS = 1 AND A.S_READING_TYPE IN ('D','I') GROUP BY A.S_EB_ID"; //0808000022 = GENERATION

public static final String GET_WEC_GENERATION_BY_FEDER_GROUP_EB_MONTH = 
	"SELECT A.S_EB_ID,SUM(N_VALUE) AS CUMGEN,SUM(N_ACTUAL_VALUE) AS TOTGEN FROM TBL_WEC_READING A, TBL_WEC_MASTER D, TBL_FEDER_MASTER B, TBL_EB_MASTER C " +
	" WHERE A.d_READING_DATE BETWEEN ? AND ? AND B.S_FEDER_ID = ? AND C.S_FEDER_ID = B.S_FEDER_ID AND A.S_EB_ID = C.S_EB_ID AND D.S_WEC_ID = A.S_WEC_ID " +
	" AND A.S_MP_ID = '0808000022' AND D.S_STATUS = 1 AND A.S_READING_TYPE IN ('D','I') GROUP BY A.S_EB_ID"; //0808000022 = GENERATION

public static final String GET_EB_MASTER_BY_FEDER_ID = 
    "SELECT S_EB_ID FROM TBL_EB_MASTER WHERE S_FEDER_ID = ? ORDER BY S_EB_ID";

public static final String GET_EB_KWH_EXP =
	"SELECT A.N_ACTUAL_VALUE,A.S_EB_ID FROM TBL_EB_READING A, TBL_EB_MASTER B WHERE A.S_EB_ID = B.S_EB_ID AND B.S_SITE_ID = ? " +
	" AND A.D_READING_DATE = ? AND b.S_STATUS = 1 AND A.S_MP_ID = '0808000010' AND A.S_READING_TYPE IN ('D','I')"; //0808000010 = KWH EXP

public static final String GET_EB_KWH_EXP_BY_EB =
	"SELECT A.N_ACTUAL_VALUE,A.S_EB_ID FROM TBL_EB_READING A, TBL_EB_MASTER B WHERE A.S_EB_ID = B.S_EB_ID AND B.S_EB_ID = ? " +
	" AND A.D_READING_DATE = ? AND b.S_STATUS = 1 AND A.S_MP_ID = '0808000010' AND A.S_READING_TYPE IN ('D','I')"; //0808000010 = KWH EXP

public static final String GET_FEDER_KWH_EXP =
	"SELECT A.N_ACTUAL_VALUE,A.S_FEDER_ID FROM TBL_FEDER_READING A, TBL_FEDER_MASTER B WHERE A.S_FEDER_ID = B.S_FEDER_ID AND B.S_SITE_ID = ? " +
	" AND A.D_READING_DATE = ? AND b.S_STATUS = 1 AND A.S_MP_ID = '0808000010' AND A.S_READING_TYPE IN ('D','I')"; //0808000010 = KWH EXP

public static final String GET_FEDER_MASTER_FOR_READING_PAGED_PART_2 =
	" AND A.S_FEDER_ID IN (SELECT B.S_FEDER_ID FROM (SELECT Z.*, ROWNUM R FROM (SELECT A.S_FEDER_ID FROM TBL_FEDER_MASTER A,TBL_FEDER_MFACTOR B " +
	" WHERE A.S_SITE_ID=? AND A.S_STATUS = 1 AND A.S_FEDER_ID = B.S_FEDER_ID AND ? BETWEEN B.D_FROM_DATE AND B.D_TO_DATE " +
	" ORDER BY S_FEDERSHORT_DESCR ) Z WHERE ROWNUM <= ?) B WHERE R >= ?)";

public static final String GET_FEDER_BY_WEC = 
	"SELECT B.S_MP_ID,B.S_FEDER_ID,B.N_VALUE,B.N_ACTUAL_VALUE,B.S_READING_TYPE,E.S_MP_UNIT FROM TBL_FEDER_READING B, TBL_WEC_MASTER A, TBL_EB_MASTER C, " +
	" TBL_FEDER_MASTER D, TBL_MP_MASTER E " +
	" WHERE B.S_FEDER_ID = D.S_FEDER_ID AND A.S_EB_ID=C.S_EB_ID AND C.S_FEDER_ID = D.S_FEDER_ID AND " +
	" A.S_WEC_ID=? AND B.D_READING_DATE = ? AND E.S_MP_ID = B.S_MP_ID AND " +
	" B.S_MP_ID NOT IN (SELECT S_MP_ID FROM TBL_MP_MASTER WHERE S_MP_UNIT = 'HOURS') " +
	" ORDER BY A.S_WEC_ID";

public static final String GET_FD_MASTER_FOR_READING =
	"SELECT B.D_READING_DATE,A.S_FEDER_ID,C.S_MP_ID,B.N_VALUE,B.N_ACTUAL_VALUE,B.S_REMARKS FROM TBL_FEDER_MASTER A LEFT OUTER JOIN " +
	" TBL_FEDER_READING B ON A.S_FEDER_ID = B.S_FEDER_ID LEFT OUTER JOIN TBL_MP_MASTER C ON " +
	" B.S_MP_ID = C.S_MP_ID WHERE A.S_SITE_ID = ? AND B.D_READING_DATE = ? AND A.S_STATUS = 1 AND C.S_STATUS = 1 AND C.S_MP_SHOW IN ('EB','BOTH') " +
	" AND C.S_READ_TYPE IN (?,'A') ";

public static final String GET_FD_MASTER_FOR_READING_MAX =
	"SELECT B.D_READING_DATE,A.S_FEDER_ID,C.S_MP_ID,B.N_VALUE,B.N_ACTUAL_VALUE,B.S_REMARKS FROM TBL_FEDER_MASTER A LEFT OUTER JOIN " +
	" TBL_FEDER_READING B ON A.S_FEDER_ID = B.S_FEDER_ID LEFT OUTER JOIN TBL_MP_MASTER C ON " +
	" B.S_MP_ID = C.S_MP_ID WHERE B.S_READING_TYPE IN (?,'I') AND A.S_SITE_ID = ? AND B.D_READING_DATE IN (select max(d_reading_date) from TBL_FEDER_READING where " +
	" S_READING_TYPE IN (?,'I') and TO_CHAR(d_reading_date,'MM') = ? and TO_CHAR(d_reading_date,'yyyy') = ? and A.S_FEDER_ID = TBL_FEDER_READING.S_FEDER_ID) AND A.S_STATUS = 1 AND C.S_STATUS = 1 " +
	" AND C.S_MP_SHOW IN ('EB','BOTH') AND C.S_READ_TYPE IN (?,'A')  " +
	" AND A.S_FEDER_ID IN (SELECT B.S_FEDER_ID FROM (SELECT Z.*, ROWNUM R FROM (SELECT A.S_FEDER_ID FROM TBL_FEDER_MASTER A, TBL_FEDER_MFACTOR B " +
	" WHERE A.S_FEDER_ID = B.S_FEDER_ID AND A.S_SITE_ID=? AND A.S_STATUS = 1 " +
	" AND ? BETWEEN B.D_FROM_DATE AND B.D_TO_DATE ORDER BY S_FEDERSHORT_DESCR ) Z WHERE ROWNUM <= ?)" +
	" B WHERE R >= ?) ORDER BY B.S_REMARKS DESC,C.N_SEQ_NO";

public static final String GET_FD_MASTER_FOR_READING_MAX_BY_ID =
	"SELECT B.D_READING_DATE FROM TBL_FEDER_MASTER A LEFT OUTER JOIN " +
	" TBL_FEDER_READING B ON A.S_FEDER_ID = B.S_FEDER_ID LEFT OUTER JOIN TBL_MP_MASTER C ON " +
	" B.S_MP_ID = C.S_MP_ID WHERE B.S_READING_TYPE IN (?,'I') AND B.D_READING_DATE IN (select max(d_reading_date) from TBL_FEDER_READING where " +
	" S_READING_TYPE IN (?,'I') and d_reading_date < ? and A.S_FEDER_ID = TBL_FEDER_READING.S_FEDER_ID) AND A.S_STATUS = 1 AND C.S_STATUS = 1 " +
	" AND C.S_MP_SHOW IN ('EB','BOTH') AND C.S_READ_TYPE IN (?,'A')  " +
	" AND A.S_FEDER_ID = ?";

public static final String GET_WEC_MASTER_FOR_READING =
	"SELECT A.S_WECSHORT_DESCR,B.D_READING_DATE,A.S_EB_ID,B.S_WEC_ID,C.S_MP_ID,B.N_VALUE,b.B.N_ACTUAL_VALUE,C.S_MP_UNIT,B.S_REMARKS " +
	" FROM TBL_WEC_MASTER A RIGHT OUTER JOIN TBL_EB_MASTER D " +
	" ON A.S_EB_ID = D.S_EB_ID LEFT OUTER JOIN " +
	" TBL_WEC_READING B ON A.S_WEC_ID = B.S_WEC_ID LEFT OUTER JOIN TBL_MP_MASTER C ON " +
	" B.S_MP_ID = C.S_MP_ID WHERE D.S_SITE_ID = ? AND B.D_READING_DATE = ? AND A.S_STATUS = 1 AND " +
	" C.S_STATUS = 1 AND C.S_MP_SHOW IN ('WEC','BOTH') AND C.S_READ_TYPE IN (?,'A') AND B.S_READING_TYPE IN('D','I') ";

public static final String GET_WEC_MASTER_FOR_READING_PAGED_PART_2 =
	" AND A.S_WEC_ID IN (SELECT B.S_WEC_ID FROM (SELECT Z.*, ROWNUM R FROM (SELECT A.S_WEC_ID,A.S_EB_ID FROM TBL_WEC_MASTER A, " +
	" TBL_EB_MASTER B WHERE (A.D_COMMISION_DATE is null OR A.D_COMMISION_DATE <= ?) AND A.S_EB_ID = B.S_EB_ID AND B.S_SITE_ID=? AND A.S_STATUS = 1 " +
	" ORDER BY A.S_WECSHORT_DESCR) Z WHERE ROWNUM <= ?) B WHERE R >= ?)";

public static final String SELECT_EB_MASTER_BY_NAME =
	"SELECT * FROM TBL_EB_MASTER WHERE S_EB_DESCRIPTION=?";

public static final String SELECT_EB_MASTER_BY_DESC =
	"SELECT * FROM TBL_EB_MASTER WHERE LTRIM(RTRIM(S_EBSHORT_DESCR))=? AND S_STATUS = 1";

public static final String SELECT_EB_MASTER_BY_DESC_NEW =
	"SELECT A.S_EB_ID, B.N_MULTI_FACTOR,B.S_TYPE,B.S_SUB_TYPE,B.S_CAPACITY FROM TBL_EB_MASTER A, TBL_EB_MFACTOR B" +
	" WHERE LTRIM(RTRIM(A.S_EBSHORT_DESCR))=? AND S_STATUS = 1 AND A.S_EB_ID = B.S_EB_ID AND ? BETWEEN B.D_FROM_DATE AND B.D_TO_DATE";

public static final String SELECT_FEDER_MASTER_BY_DESC_NEW =
	"SELECT A.S_FEDER_ID, B.N_MULTI_FACTOR,B.S_TYPE,B.S_SUB_TYPE,B.S_CAPACITY FROM TBL_FEDER_MASTER A, TBL_FEDER_MFACTOR B" +
	" WHERE LTRIM(RTRIM(A.S_FEDERSHORT_DESCR))=? AND S_STATUS = 1 AND A.S_FEDER_ID = B.S_FEDER_ID AND ? BETWEEN B.D_FROM_DATE AND B.D_TO_DATE";

public static final String SELECT_WEC_READING_BY_EBDESC = 
	" select nvl(sum(n_actual_value),0) as n_value from tbl_wec_reading, tbl_eb_master " +
	" where tbl_wec_reading.s_eb_id=tbl_eb_master.s_eb_id " +
	" and tbl_wec_reading.s_mp_id='0808000022' " +
	" and tbl_eb_master.s_ebshort_descr=? " +
	" and tbl_wec_reading.d_reading_date=?";

public static final String SELECT_WEC_READING_BY_FEDERDESC = 
	" select nvl(sum(n_actual_value),0) as n_value from tbl_wec_reading, tbl_eb_master, tbl_feder_master " +
	" where tbl_wec_reading.s_eb_id=tbl_eb_master.s_eb_id " +
	" and tbl_eb_master.s_feder_id=tbl_feder_master.s_feder_id " +
	" and tbl_wec_reading.s_mp_id='0808000022' " +
	" and tbl_feder_master.S_FEDERSHORT_DESCR=? " +
	" and tbl_wec_reading.d_reading_date=?";

public static final String SELECT_MP_MASTER_BY_DESC = 
	"SELECT * FROM TBL_MP_MASTER WHERE S_MP_DESCR=?";

public static final String S_SAP_CUSTOMER_CODE=
	"SELECT * FROM TBL_CUSTOMER_MASTER WHERE S_SAP_CUSTOMER_CODE = to_char(?)";

public static final String S_WECSHORT_DESCR=
	"SELECT * FROM TBL_WEC_MASTER WHERE S_WECSHORT_DESCR=? AND S_STATUS='1'";

public static final String S_UPLOAD_REMARKS=
	"SELECT * FROM TBL_UPLD_REMARKS WHERE S_REMARKS_ID=?";

public static final String INSERT_UPLOAD_REMARKS=
	"INSERT INTO TBL_WEC_REMARKS VALUES(SEQ_REMARKS.NEXTVAL,?,?,?)";

public static final String SELECT_UPLOAD_REMARKS=
	"SELECT * FROM TBL_WEC_REMARKS WHERE D_READING_DATE=? AND S_REMARKS_ID=? AND S_WEC_ID=?";

public static final String CHECK_UPLOAD_REMARKS=
	"SELECT * FROM TBL_UPLD_REMARKS WHERE S_REMARKS_ID=?";

public static final String CHECK_EB_READING =
	"SELECT * FROM TBL_EB_READING WHERE D_READING_DATE = ? AND S_MP_ID = ? AND S_EB_ID = ?";

public static final String CHECK_EB_READING_OF_MONTH =
	"SELECT * FROM TBL_EB_READING WHERE TO_CHAR(TO_DATE(D_READING_DATE, 'DD-MON-YYYY') ,'MM') = TO_CHAR(TO_DATE(?, 'DD-MON-YYYY') ,'MM') AND " +
		" TO_CHAR(TO_DATE(D_READING_DATE, 'DD-MON-YYYY') ,'YYYY') = TO_CHAR(TO_DATE(?, 'DD-MON-YYYY') ,'YYYY') AND S_MP_ID = ? AND S_EB_ID = ?  AND S_READING_TYPE='M'";


public static final String CHECK_FD_READING =
	"SELECT * FROM TBL_FEDER_READING WHERE D_READING_DATE = ? AND S_MP_ID = ? AND S_FEDER_ID = ? ";

public static final String CHECK_FD_READING_OF_MONTH =
	"SELECT * FROM TBL_FEDER_READING WHERE TO_CHAR(TO_DATE(D_READING_DATE, 'DD-MON-YYYY') ,'MM') = TO_CHAR(TO_DATE(?, 'DD-MON-YYYY') ,'MM') AND " +
		" TO_CHAR(TO_DATE(D_READING_DATE, 'DD-MON-YYYY') ,'YYYY') = TO_CHAR(TO_DATE(?, 'DD-MON-YYYY') ,'YYYY') AND S_MP_ID = ? AND S_FEDER_ID = ?  AND S_READING_TYPE='M' ";

public static final String CHECK_WEC_READING =
	"SELECT * FROM TBL_WEC_READING WHERE D_READING_DATE = ? AND S_MP_ID = ? AND S_WEC_ID = ?";

public static final String CHECK_EB_READING_YESTERDAY_BY_MP =
	"SELECT * FROM TBL_EB_READING WHERE D_READING_DATE = ? AND S_MP_ID = ? AND S_EB_ID = ? AND S_READING_TYPE IN ('D','I')";

public static final String CHECK_FEDER_READING_YESTERDAY_BY_MP =
	"SELECT * FROM TBL_FEDER_READING WHERE D_READING_DATE = ? AND S_MP_ID = ? AND S_FEDER_ID = ? AND S_READING_TYPE IN ('D','I')";

public static final String CHECK_EB_READING_YESTERDAY_BY_MP_MAX =
	"SELECT B.D_READING_DATE,A.S_EB_ID,C.S_MP_ID,B.N_VALUE,B.N_ACTUAL_VALUE,B.S_REMARKS FROM TBL_EB_MASTER A LEFT OUTER JOIN " +
	" TBL_EB_READING B ON A.S_EB_ID = B.S_EB_ID LEFT OUTER JOIN TBL_MP_MASTER C ON " +
	" B.S_MP_ID = C.S_MP_ID WHERE B.S_MP_ID = ? AND A.S_EB_ID = ? AND B.S_READING_TYPE IN (?,'I') AND " +
	" B.D_READING_DATE IN (SELECT MAX(D_READING_DATE) FROM TBL_EB_READING WHERE " +
	" S_READING_TYPE IN (?,'I') AND D_READING_DATE <= ? AND B.S_MP_ID = ? AND A.S_EB_ID = ? and A.S_EB_ID = TBL_EB_READING.S_EB_ID) " +
	" AND A.S_STATUS = 1 AND C.S_STATUS = 1 AND C.S_MP_SHOW IN ('EB','BOTH')  ";

public static final String CHECK_FEDER_READING_YESTERDAY_BY_MP_MAX =
	"SELECT B.D_READING_DATE,A.S_FEDER_ID,C.S_MP_ID,B.N_VALUE,B.N_ACTUAL_VALUE,B.S_REMARKS FROM TBL_FEDER_MASTER A LEFT OUTER JOIN " +
	" TBL_FEDER_READING B ON A.S_FEDER_ID = B.S_EB_ID LEFT OUTER JOIN TBL_MP_MASTER C ON " +
	" B.S_MP_ID = C.S_MP_ID WHERE B.S_MP_ID = ? AND A.S_FEDER_ID = ? AND B.S_READING_TYPE IN (?,'I') AND " +
	" B.D_READING_DATE IN (SELECT MAX(D_READING_DATE) FROM TBL_FEDER_READING WHERE " +
	" S_READING_TYPE IN (?,'I') AND D_READING_DATE <= ? AND B.S_MP_ID = ? AND A.S_FEDER_ID = ? and A.S_FEDER_ID = TBL_FEDER_READING.S_FEDER_ID) " +
	" AND A.S_STATUS = 1 AND C.S_STATUS = 1 AND C.S_MP_SHOW IN ('EB','BOTH')  ";

public static final String CHECK_FD_READING_YESTERDAY_BY_MP =
	"SELECT * FROM TBL_FEDER_READING WHERE D_READING_DATE = ? AND S_MP_ID = ? AND S_feder_ID = ? AND S_READING_TYPE IN ('D','I')";

public static final String CHECK_WEC_READING_YESTERDAY_BY_MP =
	"SELECT * FROM TBL_WEC_READING WHERE D_READING_DATE = ? AND S_MP_ID = ? AND S_WEC_ID = ? AND S_READING_TYPE IN ('D','I')";

public static final String GET_EB_READING_YESTERDAY =
	"SELECT * FROM TBL_EB_READING WHERE D_READING_DATE = ? AND S_EB_ID = ?";

public static final String GET_WEC_BY_CUSTOMER_ID =
	"SELECT * FROM TBL_WEC_MASTER WHERE S_CUSTOMER_ID = ? AND S_STATUS='1' ORDER BY S_WECSHORT_DESCR";

public static final String GET_EB_BY_CUSTOMER_ID =
	//"SELECT * FROM TBL_WEC_MASTER WHERE S_CUSTOMER_ID = ? AND S_STATUS='1' ORDER BY S_WECSHORT_DESCR";
	"SELECT  DISTINCT TBL_WEC_MASTER.S_EB_ID, TBL_EB_MASTER.S_EBSHORT_DESCR "+
	"FROM    TBL_WEC_MASTER,TBL_EB_MASTER "+ 
	"WHERE   TBL_WEC_MASTER.S_EB_ID = TBL_EB_MASTER.S_EB_ID "+
	"AND     TBL_WEC_MASTER.S_CUSTOMER_ID = ? "+ 
	"AND     TBL_WEC_MASTER.S_STATUS in('1','9') "+
	"ORDER BY TBL_EB_MASTER.S_EBSHORT_DESCR";

public static final String GET_EB_BY_CUSTOMER_ID_1 =
	//"SELECT * FROM TBL_WEC_MASTER WHERE S_CUSTOMER_ID = ? AND S_STATUS='1' ORDER BY S_WECSHORT_DESCR";
	"SELECT  DISTINCT TBL_WEC_MASTER.S_EB_ID, TBL_EB_MASTER.S_EBSHORT_DESCR "+
	"FROM    TBL_WEC_MASTER,TBL_EB_MASTER "+ 
	"WHERE   TBL_WEC_MASTER.S_EB_ID = TBL_EB_MASTER.S_EB_ID "+
	"AND     TBL_WEC_MASTER.S_CUSTOMER_ID = ? "+ 
	"AND     TBL_WEC_MASTER.S_STATUS ='1' "+
	"ORDER BY TBL_EB_MASTER.S_EBSHORT_DESCR";

public static final String GET_WEC_BY_EB_ID =
	"SELECT * FROM TBL_WEC_MASTER WHERE S_EB_ID = ? AND S_STATUS in ('1','9') ORDER BY S_WECSHORT_DESCR";

/*public static final String GET_WEC_TO_BY_EB_ID =
		"SELECT TBL_WEC_MASTER.* "+
	  	"FROM TBL_WEC_MASTER "+
		"WHERE TBL_WEC_MASTER.S_EB_ID = ? "+
	  	"AND TBL_WEC_MASTER.S_STATUS='1' "+
		"AND (SELECT S_WEC_ID FROM TBL_WEC_MASTER WHERE S_EB_ID=?) NOT IN (SELECT S_WEC_ID FROM TBL_WEC_READING) "+ 
		"ORDER BY TBL_WEC_MASTER.S_WECSHORT_DESCR";*/
/*public static final String GET_WEC_TO_BY_EB_ID =
		"SELECT  TBL_WEC_MASTER.* FROM TBL_WEC_MASTER "+ 
		"WHERE   S_EB_ID =? "+
		"AND     S_WEC_ID NOT IN (SELECT DISTINCT S_WEC_ID FROM TBL_WEC_READING WHERE D_READING_DATE >= '01-JAN-2011' AND S_EB_ID =?)";*/

public static final String GET_WEC_TO_BY_EB_ID =
"SELECT  TBL_WEC_MASTER.* FROM TBL_WEC_MASTER "+ 
"WHERE   S_EB_ID =? ";

public static final String GET_FD_READING_YESTERDAY =
	"SELECT * FROM TBL_FEDER_READING WHERE D_READING_DATE = ? AND S_FEDER_ID = ?";

public static final String GET_WEC_READING_YESTERDAY =
	"SELECT * FROM TBL_WEC_READING WHERE D_READING_DATE = ? AND S_WEC_ID = ?";

public static final String CHECK_WEC_READING_FOR_REMARKS =
	"SELECT * FROM TBL_WEC_READING WHERE D_READING_DATE = ? AND S_WEC_ID = ? AND S_READING_TYPE IN (?,?) ORDER BY S_REMARKS";

public static final String CHECK_WEC_READING_FOR_TECH_REMARKS =
	"SELECT * FROM TBL_WEC_READING WHERE D_READING_DATE = ? AND S_WEC_ID = ? ORDER BY S_REMARKS";

public static final String CHECK_FD_READING_FOR_REMARKS =
	"SELECT * FROM TBL_FEDER_READING WHERE D_READING_DATE = ? AND S_FEDER_ID = ? AND S_READING_TYPE IN (?,?) ORDER BY S_REMARKS";

public static final String CHECK_EB_READING_FOR_REMARKS =
	"SELECT * FROM TBL_EB_READING WHERE D_READING_DATE = ? AND S_EB_ID = ? AND S_READING_TYPE IN (?,?) ORDER BY S_REMARKS";

public static final String INSERT_EB_READING = 
	"Insert into TBL_EB_READING(S_READING_ID,D_READING_DATE,S_MP_ID,S_EB_ID,S_READING_TYPE,N_VALUE, "+
	"S_CREATED_BY,S_LAST_MODIFIED_BY,D_CREATED_DATE,D_LAST_MODIFIED_DATE,N_ACTUAL_VALUE,S_REMARKS,S_CUSTOMER_ID,N_PUBLISH) values "+
	"(?,?,?,?,?,?,?,?,SYSDATE,SYSDATE,?,to_char(?),?,?)";

/*public static final String INSERT_EB_READING_INITIAL = 
	"Insert into TBL_EB_READING(S_READING_ID,D_READING_DATE,S_MP_ID,S_EB_ID,S_READING_TYPE,N_VALUE, "+
	"S_CREATED_BY,S_LAST_MODIFIED_BY,D_CREATED_DATE,D_LAST_MODIFIED_DATE,S_REMARKS,S_CUSTOMER_ID) values "+
	"(?,?,?,?,?,?,?,?,SYSDATE,SYSDATE,to_char(?),?)";*/

public static final String INSERT_FEDER_READING = 
	"Insert into TBL_FEDER_READING(S_READING_ID,D_READING_DATE,S_MP_ID,S_FEDER_ID,S_READING_TYPE,N_VALUE, "+
	"S_CREATED_BY,S_LAST_MODIFIED_BY,D_CREATED_DATE,D_LAST_MODIFIED_DATE,N_ACTUAL_VALUE,S_REMARKS) values "+
	"(?,?,?,?,?,?,?,?,SYSDATE,SYSDATE,?,to_char(?))";

/*public static final String INSERT_FEDER_READING_INITIAL = 
	"Insert into TBL_FEDER_READING(S_READING_ID,D_READING_DATE,S_MP_ID,S_FEDER_ID,S_READING_TYPE,N_VALUE, "+
	"S_CREATED_BY,S_LAST_MODIFIED_BY,D_CREATED_DATE,D_LAST_MODIFIED_DATE,S_REMARKS) values "+
	"(?,?,?,?,?,?,?,?,SYSDATE,SYSDATE,to_char(?))";*/

public static final String INSERT_WEC_READING = 
	"Insert into TBL_WEC_READING(S_READING_ID,D_READING_DATE,S_MP_ID,S_WEC_ID,S_EB_ID,S_CUSTOMER_ID,N_VALUE, "+
	"S_CREATED_BY,S_LAST_MODIFIED_BY,D_CREATED_DATE,D_LAST_MODIFIED_DATE,N_ACTUAL_VALUE,S_READING_TYPE,N_PUBLISH) values "+
	"(?,?,?,?,?,?,?,?,?,SYSDATE,SYSDATE,?,?,?)";

/*public static final String INSERT_WEC_READING_INITIAL = 
	"Insert into TBL_WEC_READING(S_READING_ID,D_READING_DATE,S_MP_ID,S_WEC_ID,S_EB_ID,S_CUSTOMER_ID,N_VALUE, "+
	"S_CREATED_BY,S_LAST_MODIFIED_BY,D_CREATED_DATE,D_LAST_MODIFIED_DATE,S_READING_TYPE) values "+
	"(?,?,?,?,?,?,?,?,?,SYSDATE,SYSDATE,?)";*/

public static final String DELETE_EB_DATA_1 = 
	"DELETE FROM TBL_EB_READING WHERE  S_EB_ID = ? AND D_READING_DATE BETWEEN ? AND ?";

public static final String DELETE_EB_DATA = 
	"DELETE FROM TBL_EB_READING WHERE S_MP_ID = ? AND S_EB_ID = ? AND D_READING_DATE BETWEEN ? AND ?";

public static final String DELETE_FEDER_DATA = 
	"DELETE FROM TBL_FEDER_READING WHERE S_MP_ID = ? AND S_FEDER_ID = ? AND D_READING_DATE BETWEEN ? AND ?";

public static final String DELETE_FEDER_DATA_1 = 
	"DELETE FROM TBL_FEDER_READING WHERE S_FEDER_ID = ? AND D_READING_DATE BETWEEN ? AND ?";

public static final String DELETE_EB_DATA_BY_FEDER = 
	"DELETE FROM TBL_EB_READING WHERE S_MP_ID = ? AND D_READING_DATE BETWEEN ? AND ? AND S_EB_ID IN (SELECT S_EB_ID FROM TBL_EB_MASTER" +
	" WHERE S_FEDER_ID = ?)";
public static final String DELETE_EB_DATA_BY_FEDER_1 = 
	"DELETE FROM TBL_EB_READING WHERE  D_READING_DATE BETWEEN ? AND ? AND S_EB_ID IN (SELECT S_EB_ID FROM TBL_EB_MASTER" +
	" WHERE S_FEDER_ID = ?)";

public static final String DELETE_WEC_DATA = 
	"DELETE FROM TBL_WEC_READING WHERE S_MP_ID = ? AND S_WEC_ID = ? AND D_READING_DATE BETWEEN ? AND ?";

public static final String DELETE_WEC_DATA_1 = 
	"DELETE FROM TBL_WEC_READING WHERE  S_WEC_ID = ? AND D_READING_DATE BETWEEN ? AND ?";


public static final String UPDATE_EB_STATUS = 
    "UPDATE TBL_EB_MASTER  SET S_STATUS=? ,d_Last_Modified_Date=sysdate, s_Last_Modified_By=? WHERE S_EB_ID = ? ";

public static final String UPDATE_FD_PUBLISH = 
	"UPDATE TBL_FEDER_READING SET N_PUBLISH = ? WHERE S_FEDER_ID IN (SELECT S_FEDER_ID FROM TBL_FEDER_MASTER WHERE S_SITE_ID = ?) AND  " +
	" D_READING_DATE = ?";
    
public static final String UPDATE_EB_TRANSFER = 
	"UPDATE TBL_EB_READING SET S_EB_ID = ?,S_CUSTOMER_ID=? WHERE S_EB_ID =? AND D_READING_DATE >= ?";

public static final String UPDATE_WEC_TRANSFER = 
	"UPDATE TBL_WEC_READING SET S_CUSTOMER_ID = ?, S_WEC_ID = ?, S_EB_ID=?, S_LAST_MODIFIED_BY=?, D_LAST_MODIFIED_DATE=SYSDATE WHERE  S_WEC_ID = ? AND D_READING_DATE >= ?";

public static final String UPDATE_EB_MASTER =
	" UPDATE TBL_EB_MASTER SET S_EB_ID = ? WHERE S_EB_ID = ? AND S_WEC_ID = ? ";

public static final String UPDATE_EB_MASTER_1 =
	"UPDATE TBL_EB_MASTER SET D_TRANSFER_DATE = ?,S_EB_ID_TO = ?,S_REMARKS=?,S_STATUS='9'  WHERE S_EB_ID = ? ";

public static final String SELECT_CUSTOMER_DETAIL =
	" SELECT S_CUSTOMER_ID FROM TBL_EB_MASTER WHERE S_EB_ID = ?";


public static final String UPDATE_WEC_MASTER =
	" UPDATE TBL_WEC_MASTER SET S_CUSTOMER_ID = ? WHERE S_CUSTOMER_ID = ? AND S_WEC_ID = ?";

public static final String UPDATE_WEC_MASTER_1 =
	" UPDATE TBL_WEC_MASTER SET D_TRANSFER_DATE = ?,S_WEC_ID_TO=?,S_REMARKS=?,S_STATUS='9'  WHERE S_WEC_ID = ?";

public static final String UPDATE_EB_PUBLISH = 
	"UPDATE TBL_EB_READING SET N_PUBLISH = ? WHERE S_EB_ID IN (SELECT S_EB_ID FROM TBL_EB_MASTER WHERE S_SITE_ID = ?) AND  " +
	" D_READING_DATE = ?";
    
public static final String UPDATE_WEC_PUBLISH =
	" UPDATE TBL_WEC_READING SET N_PUBLISH = ? WHERE S_WEC_ID IN (SELECT A.S_WEC_ID FROM TBL_WEC_MASTER A, TBL_EB_MASTER B WHERE " +
	" A.S_EB_ID = B.S_EB_ID AND B.S_SITE_ID = ?) AND D_READING_DATE = ?";

public static final String UPDATE_SCADA_WEC_PUBLISH =
	"UPDATE TBL_WEC_READING_FACT "+
	"SET 	N_PUBLISH=? "+
	"WHERE 	S_SITE_ID=? "+
	"AND 	D_READING_DATE=? ";
	
public static final String UPDATE_FD_STATUS = 
    "UPDATE TBL_FEDER_MASTER  SET S_STATUS=? ,d_Last_Modified_Date=sysdate, s_Last_Modified_By=? WHERE S_FEDER_ID = ? ";

public static final String UPDATE_WEC_STATUS = 
    "UPDATE TBL_WEC_MASTER  SET S_STATUS=? ,d_Last_Modified_Date=sysdate, s_Last_Modified_By=? WHERE S_WEC_ID = ? ";

public static final String UPDATE_EB_READING = 
    "UPDATE TBL_EB_READING SET N_VALUE=? ,N_ACTUAL_VALUE=?,S_LAST_MODIFIED_BY=?,D_LAST_MODIFIED_DATE=sysdate " +
    " WHERE S_READING_ID = ?";

/*public static final String UPDATE_EB_READING_INITIAL = 
    "UPDATE TBL_EB_READING SET N_VALUE=? ,S_LAST_MODIFIED_BY=?,D_LAST_MODIFIED_DATE=sysdate " +
    " WHERE S_READING_ID = ?";*/

public static final String UPDATE_FD_READING = 
    "UPDATE TBL_FEDER_READING SET N_VALUE=? ,N_ACTUAL_VALUE=?,S_LAST_MODIFIED_BY=?,D_LAST_MODIFIED_DATE=sysdate " +
    " WHERE S_READING_ID = ?";

public static final String INSERT_UPDATE_QUERY = 
    "INSERT INTO TBL_UPDATE_QUERY VALUES(SEQ_TBL_UPDATE_QUERY.NEXTVAL,?,?,?,?,SYSDATE)";

/*public static final String UPDATE_FD_READING_INITIAL = 
    "UPDATE TBL_FEDER_READING SET N_VALUE=? ,S_LAST_MODIFIED_BY=?,D_LAST_MODIFIED_DATE=sysdate " +
    " WHERE S_READING_ID = ?";*/

public static final String UPDATE_WEC_READING = 
    "UPDATE TBL_WEC_READING SET N_VALUE=? ,N_ACTUAL_VALUE=?,S_LAST_MODIFIED_BY=?,D_LAST_MODIFIED_DATE=sysdate " +
    " WHERE S_READING_ID = ?";

/*public static final String UPDATE_WEC_READING_INITIAL = 
    "UPDATE TBL_WEC_READING SET N_VALUE=? ,S_LAST_MODIFIED_BY=?,D_LAST_MODIFIED_DATE=sysdate " +
    " WHERE S_READING_ID = ?";*/

public static final String UPDATE_WEC_REMARKS = 
    "UPDATE TBL_WEC_READING SET S_REMARKS=TRIM(?), S_LAST_MODIFIED_BY=?,D_LAST_MODIFIED_DATE=sysdate " +
    " WHERE S_READING_ID = ?";

public static final String UPDATE_FEDER_REMARKS = 
    "UPDATE TBL_FEDER_READING SET S_REMARKS=TRIM(?), S_LAST_MODIFIED_BY=?,D_LAST_MODIFIED_DATE=sysdate " +
    " WHERE S_READING_ID = ?";

public static final String UPDATE_EB_REMARKS = 
    "UPDATE TBL_EB_READING SET S_REMARKS=TRIM(?), S_LAST_MODIFIED_BY=?,D_LAST_MODIFIED_DATE=sysdate " +
    " WHERE S_READING_ID = ?";

public static final String UPDATE_EB_BY_FEDER_REMARKS = 
	"UPDATE TBL_EB_READING SET S_REMARKS=?, S_LAST_MODIFIED_BY=?,D_LAST_MODIFIED_DATE=sysdate " +
	" WHERE ";

public static final String INSERT_WEC_DATA =
	"{call PRC_INSERT_WEC(?,?,?,?,?,?,?,?,?,?)}";

	public SiteUserSQLC() {
    }
}
