package com.enercon.global.utils;

public class CallSchedulerXMLSQLC 
{
	public static final String CURR_CUM_GEN_ALL = "SELECT SUM(N_ACTUAL_VALUE) AS TOTALCURCUM FROM TBL_WEC_READING WHERE  D_READING_DATE > "+
					"(SELECT   D_DATA_UPTO FROM TBL_ACTUAL_CUMULATIVE_GEN  WHERE S_DATA_TYPE='ALL') AND D_READING_DATE < SYSDATE AND S_MP_ID='0808000022' AND N_PUBLISH=1";
	
	public static final String TOTAL_CUM_GEN = "SELECT N_GENERATION,S_DATA_TYPE  FROM TBL_ACTUAL_CUMULATIVE_GEN";
	  
	public static final String CHECK_CUM_GEN_REGULAR = "SELECT SUM(N_GENERATION) AS TOTALGEN FROM TBL_ACTUAL_CUMULATIVE_GEN WHERE   S_DATA_TYPE='REGULAR' AND TO_DATE(D_DATA_UPTO)=TO_DATE(SYSDATE-1)";
	
	public static final String DELETE_GEN_REGULAR = "DELETE FROM TBL_ACTUAL_CUMULATIVE_GEN WHERE   S_DATA_TYPE='REGULAR' AND TO_DATE(D_DATA_UPTO)<=TO_DATE(SYSDATE-1)";
	
	public static final String INSERT_CUM_GEN_REGULAR = "INSERT INTO TBL_ACTUAL_CUMULATIVE_GEN VALUES(SYSDATE-1,'Regualr Data upto date',?,'REGULAR')";
	
	public static final String TOTAL_YSTAYERD_GEN = "SELECT SUM(N_ACTUAL_VALUE) AS TOTALT_YTD_GEN  FROM TBL_WEC_READING WHERE TO_DATE(D_READING_DATE)=TO_DATE(SYSDATE-1) AND S_MP_ID='0808000022' ";
}