package com.enercon.projects.dao;

public class ProjectSQLC 
{

	public static final String GET_ACTIVITY_TRANSACTION =
		"SELECT A.*,B.* FROM TBL_ACTIVITY_TRANSACTION A,TBL_PROJECT_ACTIVITY B WHERE A.S_ACTIVITY_ID=B.S_ACTIVITY_ID";

	public static final String GET_MATERIAL_TRANSACTION =
		"SELECT A.*,B.*,C.* FROM TBL_MATERIAL_TRANSACTION A,TBL_MATERIAL_MASTER B,TBL_PROJECT_MASTER C WHERE A.S_PROJECT_ID=C.S_PROJECT_ID AND  A.S_MATERIAL_ID=B.S_MATERIAL_ID";
	public static final String GET_PROJECT_ACTIVITY =
		"SELECT A.*,B.* FROM TBL_PROJECT_MASTER A,TBL_PROJECT_ACTIVITY B WHERE A.S_PROJECT_ID=B.S_PROJECT_ID";
	public static final String GET_PROJECT_GRID =
		"SELECT A.*,B.S_CUSTOMER_NAME,C.S_SITE_NAME FROM TBL_PROJECT_MASTER A,TBL_CUSTOMER_MASTER B,TBL_SITE_MASTER C WHERE A.S_CUSTOMER_ID=B.S_CUSTOMER_ID AND C.S_SITE_ID=A.S_SITE_ID";
	
	public static final String CHECK_MATERIAL_MASTER =
		"SELECT * FROM TBL_MATERIAL_MASTER WHERE S_MATERIAL_DESC = ? AND S_MATERIAL_NO=? AND S_MATERIAL_ID <> ?";
	
	public static final String INSERT_MATERIAL = 
	    "INSERT INTO TBL_MATERIAL_MASTER(S_MATERIAL_ID,S_MATERIAL_DESC,S_MATERIAL_NO,S_CREATED_BY,S_LAST_MODIFIED_By,D_CREATED_DATE,D_LAST_MODIFIED_DATE)" +
	    "VALUES(?,?,?,?,?,SYSDATE,SYSDATE)";
	public static final String UPDATE_MATERIAL = 
	    "UPDATE TBL_MATERIAL_MASTER  SET S_MATERIAL_DESC=? ,S_MATERIAL_NO=? ,d_Last_Modified_Date=sysdate , s_Last_Modified_By=? WHERE S_MATERIAL_ID = ? ";
	
	public static final String SELECT_MATERIAL_MASTER =
		"SELECT * FROM TBL_MATERIAL_MASTER";
	public static final String SELECT_MATERIAL_MASTER_BY_ID =
		"SELECT * FROM TBL_MATERIAL_MASTER WHERE S_MATERIAL_ID = ?";
	public static final String GET_PROJECT_ID =
		"SELECT S_PROJECT_ID,S_PROJECT_DEFINITION FROM TBL_PROJECT_MASTER WHERE S_CUSTOMER_ID = ?";
	
	public static final String GET_PROJECT_HEADING =
		"select PM.S_PROJECT_ID,PM.S_PROJECT_DEFINITION,PM.S_PROJECT_DESC,PM.N_WEC_QUANTITY,PM.S_WECTYPE,PM.S_WEC_CAPACITY,SM.S_SITE_NAME,STM.S_STATE_NAME from tbl_Project_Master PM,"+
		" tbl_Site_Master SM,tbl_State_Master STM where PM.s_customer_id = ? and PM.s_project_Id = ? and PM.S_SITE_ID = SM.S_SITE_ID and SM.S_STATE_ID = STM.S_STATE_ID";

	public static final String GET_PROJECT_PARTA =
		"select  AM.N_ACTIVITY_WEC_LEVEL,AM.S_ACTIVITY_DESC,D_PLAN_STARTDATE,D_PLAN_ENDDATE, D_ACTUAL_STARTDATE,D_ACTUAL_ENDDATE from TBL_PROJECT_ACTIVITY AM,TBL_ACTIVITY_TRANSACTION ATr "+ 
        " where AM.S_ACTIVITY_ID = ATr.S_ACTIVITY_ID and AM.S_PROJECT_ID = ? and AM.N_ACTIVITY_WEC_LEVEL=? and  AM.S_ACTIVITY_PART_DISP = 'B' "+
        " order by AM.N_ACTIVITY_DISP_ORDER";

	/*public static final String GET_PROJECT_PARTB =
		"select AM.S_ACTIVITY_DESC,D_PLAN_STARTDATE,D_PLAN_ENDDATE, D_ACTUAL_STARTDATE,D_ACTUAL_ENDDATE,S_ACTIVITY_REMARKS,S_ACTIVITY_ACTUAL_STATUS from TBL_PROJECT_ACTIVITY AM,TBL_ACTIVITY_TRANSACTION ATr "+
		"where AM.S_ACTIVITY_ID = ATr.S_ACTIVITY_ID and AM.S_PROJECT_ID = ? and AM.S_ACTIVITY_PART_DISP = 'C' and AM.N_ACTIVITY_WEC_LEVEL = 0 "+
		"order by AM.N_ACTIVITY_DISP_ORDER";*/
}
